/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_es_project_MainActivity */

#ifndef _Included_com_example_es_project_MainActivity
#define _Included_com_example_es_project_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_es_project_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_es_project_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_es_project_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_es_1project_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
